version: "3"
services:
  website:
    build: .
    command: overmind start && rm -rf .overmind.sock
    environment:
      - OVERMIND_PROCFILE=Procfile.dev
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/src
