# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='copy',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
